### PR TITLE
lifecycle: define new and default users for the ROCK

### PR DESCRIPTION
**Pull request by cjdcordeiro**
Adds the properties `users` and `default_user` to rockcraft.yaml, allowing for the build-time creation of new users, as well as for the configuration of the default runtime user for the container image.

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----
fixes https://github.com/canonical/rockcraft/issues/23

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
ping @valentincanonical

**Comment by gruyaume** [comment]
Would this feature work on the `bare` base as well?

**Comment by cjdcordeiro** [comment]
> Would this feature work on the `bare` base as well?

this PR will most likely be dropped. The most recent discussions have us looking into setting the default OCI user, only, from a well-known list of users. The actual setting of private users will be postponed.

**Comment by sergiusens** [comment]
I am closing this for now to avoid confusion

**Pull request closed without merging**
