### PR TITLE
requirements: update craft-archives

### PR DESCRIPTION
**Pull request by tigarmo**
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by lengau — APPROVED** [review]
:tada:

**Comment by lengau** [comment]
@tigarmo Do you know if someone's working on those spread test failures? They're obviously not related to this, but having these spread tests be flaky isn't the greatest...

**Comment by tigarmo** [comment]
I think this failure is known/being worked on upstream possibly: `providers error: Incompatible base detected: Expected OS 'Ubuntu', found None.`. I don't know if there's anything we can do to address it on our side

**Comment by mr-cal** [comment]
Here's the upstream bug: https://github.com/lxc/lxd/issues/11422

**Review by mr-cal — APPROVED** [review]

**Pull request merged**
