### PR TITLE
fix: craft-cli branch ref to main

### PR DESCRIPTION
**Pull request by yanksyoon**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Fixes: https://github.com/canonical/rockcraft/issues/621

### CODE REVIEW

**Comment by yanksyoon** [comment]
Tests are failing due to ref to rockcraft branch in the `craft-application`. PR: https://github.com/canonical/craft-application/pull/369

**Comment by tigarmo** [comment]
We'll fix this soon with properly released versions of the tools. May I ask why you need development rockcraft?

**Comment by yanksyoon** [comment]
@tigarmo thank you! Shall I close the PRs related to the this issue?
The reason I need these are for our operator workflows: https://github.com/canonical/operator-workflows/pull/370 in which we have a test to clone rockcraft repo and build the version to test the feature where we can specify rockcraft refs.

**Comment by yanksyoon** [comment]
Will do! Thank you!

**Pull request closed without merging**
