### PR TITLE
chore: use Init command and service from upstream

### PR DESCRIPTION
**Pull request by tigarmo**
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by dariuszd21 — APPROVED** [review]
Thank you!

**Review by dariuszd21 — APPROVED** [review]
Thanks!

**Review by mr-cal — APPROVED** [review]

**Comment by mr-cal** [comment]
I think `refactor` may be more precise than `chore` as the commit category.

**Comment by tigarmo** [comment]
> I think `refactor` may be more precise than `chore` as the commit category.

In the end I updated the commit to `feat` as there is new functionality (the `--project-dir` argument)

**Pull request merged**
