### PR TITLE
build(deps): bump craft-providers to 1.23.0

### PR DESCRIPTION
**Pull request by mr-cal**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### 1.23.0 (2024-02-28)

- Update base compatibility tag to ``base-v7``
- Use ``buildd`` daily for Ubuntu 24.04 (Noble) and Ubuntu devel images
- Ensure apt installs non-interactively

### CODE REVIEW

**Comment by mr-cal** [comment]
I see chisel and libc6 errors in the spread tests and similar errors on a different PR, so I'm not sure what tests were already passing or failing!

**Comment by tigarmo** [comment]
@mr-cal can you re-seat this onto `hotfix/1.2`? I think we'll need to release a patch 1.2.2

**Comment by tigarmo** [comment]
what the heck
where are the other checks??

**Review by tigarmo — APPROVED** [review]
failures are unrelated

**Pull request merged**
