### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by valentincanonical**
- Snap install requires 'sudo' rights
- Document --verbose option for 'rockcraft pack'
- Add link on how to install Docker on linux (with Snaps)
- Clarify what the hello_1.0.rock file is

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by cjdcordeiro — APPROVED** [review]
@tigarmo @mr-cal @sergiusens @cmatsuoka could one of you pls merge this :)

**Review by tigarmo — APPROVED** [review]

**Comment by tigarmo** [comment]
@cjdcordeiro @valentincanonical do either of you want to fix the conflicts?

**Comment by cjdcordeiro** [comment]
hum I can't seen them (I don't have write access)

**Comment by valentincanonical** [comment]
@tigarmo can't see any conflict either! — is this one of these "wait long enough and problems will fix themselves" situations? or am I missing something?

**Comment by tigarmo** [comment]
Oh I fixed the conflict last week, the only issue left is the cla-check: https://github.com/canonical/rockcraft/actions/runs/3478866973/jobs/5816732614
Is valentincanonical not a member of the Canonical org?

**Pull request merged**
