### PR TITLE
chore: update pebble to latest/stable

### PR DESCRIPTION
**Pull request by tigarmo**
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by tigarmo** [comment]
@cjdcordeiro we got a spread failure:

```
2023-10-05T14:39:28.4386183Z 2023-10-05 14:39:28 WARNING: oct051417-476965 (google:ubuntu-22.04-64:tests/spread/general/big) running late. Current output:
2023-10-05T14:39:28.4387090Z -----
2023-10-05T14:39:28.4387429Z (... 124 lines above ...)
2023-10-05T14:39:28.4387896Z + rm big_latest_amd64.rock
2023-10-05T14:39:28.4388817Z + docker images
2023-10-05T14:39:28.4389637Z REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
2023-10-05T14:39:28.4390181Z big          latest    0eac35ca0a58   7 hours ago   85.2MB
2023-10-05T14:39:28.4390581Z + MATCH /tmp
2023-10-05T14:39:28.4392272Z + docker run --rm big:latest
2023-10-05T14:39:28.4392915Z 2023-10-05T14:35:29.653Z [pebble] Started daemon.
2023-10-05T14:39:28.4393843Z 2023-10-05T14:35:29.655Z [pebble] POST /v1/services 537.88µs 500
2023-10-05T14:39:28.4394636Z 2023-10-05T14:35:29.655Z [pebble] Cannot start default services: cannot parse layer "big": yaml: unmarshal errors:
2023-10-05T14:39:28.4395374Z   line 10: field working-dir not found in type plan.Service
```

Does `latest/stable` pebble support `working-dir`? Its [this](https://github.com/canonical/rockcraft/blob/main/tests/spread/general/big/rockcraft.yaml#L20) test

**Comment by cjdcordeiro** [comment]
@tigarmo nop, it doesn't. it's still v1.2.0. The promotion to stable is manual. I could do it now. But I wonder if we should instead use `latest/candidate` in Rockcraft. Basically, `edge` is updated with every commit to `master`. Then `candidate` is updated on every Pebble release (`beta` points to `candidate`). Finally, promotions to `stable` are manual, and I'm afraid there isn't a policy on when to do it.

I propose using `candidate` for now, cause that way we'll always get officially released Pebble versions in a timely manner.

**Comment by sergiusens** [comment]
We can use candidate, but ideally we should be using stable in order to reach 1.0

**Review by sergiusens — APPROVED** [review]

**Review by cjdcordeiro — APPROVED** [review]
short and sweet. thanks!

**Pull request merged**
