### PR TITLE
docs: create separate chisel documentation

### PR DESCRIPTION
**Pull request by dboddie**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]
this doesn't deserve to be a draft anymore :-)

**Review by cjdcordeiro — APPROVED** [review]
thanks for this!

I'm approving, although there's a small hiccup:
 - the _static assets are being included via their absolute path in the server, which means they won't render in GitHub. Is there a strong reason not to use relative paths instead?

**Comment by dboddie** [comment]
>     * the _static assets are being included via their absolute path in the server, which means they won't render in GitHub. Is there a strong reason not to use relative paths instead?

I'll change them to be relative.

**Review by cjdcordeiro — APPROVED** [review]
awesome thanks

**Pull request merged**
