### PR TITLE
docs: use conf.py to create docs common directories

### PR DESCRIPTION
**Pull request by lengau**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by dboddie — APPROVED** [review]

**Review by SamirPS — APPROVED** [review]

**Comment by SamirPS** [comment]
If you add this change, do we still need the mkdocs script in the tools folder?

**Review by sergiusens — APPROVED** [review]
thank you, for some reason the linters were not marked as required!

**Comment by sergiusens** [comment]
I added new ignores, to links, sorted the word list, removed spurious adds and added new words to be ignored

**Comment by sergiusens** [comment]
the tests that tests the how to to build docs is still failing though...

**Comment by sergiusens** [comment]
@dboddie or @SamirPS do you know what this is about?

```
 make -C docs html
make[1]: Entering directory '/rockcraft/docs'
. env/bin/activate; sphinx-build -c . -b dirhtml "." "_build" -w warnings.txt -q 

Theme error:
An error happened in rendering the page explanation/chisel.
Reason: UndefinedError("'product_tag' is undefined")
make[1]: *** [Makefile:26: html] Error 2
make[1]: Leaving directory '/rockcraft/docs'
make: *** [Makefile:56: docs] Error 2
```
https://github.com/canonical/rockcraft/actions/runs/5663124850/job/15344489707?pr=332#step:5:405

**Comment by sergiusens** [comment]
> @dboddie or @SamirPS do you know what this is about?
> 
> ```
>  make -C docs html
> make[1]: Entering directory '/rockcraft/docs'
> . env/bin/activate; sphinx-build -c . -b dirhtml "." "_build" -w warnings.txt -q 
> 
> Theme error:
> An error happened in rendering the page explanation/chisel.
> Reason: UndefinedError("'product_tag' is undefined")
> make[1]: *** [Makefile:26: html] Error 2
> make[1]: Leaving directory '/rockcraft/docs'
> make: *** [Makefile:56: docs] Error 2
> ```
> 
> https://github.com/canonical/rockcraft/actions/runs/5663124850/job/15344489707?pr=332#step:5:405

Fixed in [[aa9ea95](https://github.com/canonical/rockcraft/pull/332/commits/aa9ea95be9c9fcc23b2c7d358e007d9948960bb5)](https://github.com/canonical/rockcraft/pull/332/commits/85284baf59dc5153e4a2c05d0b56af00c3810281), we shouldn't be constantly updating in a non controlled manner

@cjdcordeiro ^

**Comment by dboddie** [comment]
The starter pack was updated to include product tag and page information. The `conf.py` file needs to supply these things.

**Pull request merged**
