### PR TITLE
Merge craft-application update into main

### PR DESCRIPTION
**Pull request by tigarmo**
The update to the latest craft-application update was done over time in this `feature/craft-application` branch, which is now ready to be integrated back into main. Only the latest commit needs to be reviewed because we might as well update to the very new `2.4.0` - all other commits have already been reviewed in various past PRs.

### CODE REVIEW

**Comment by cmatsuoka** [comment]
> Only the latest commit needs to be reviewed

Is this the one that updates craft-application to 2.4.0?

**Comment by tigarmo** [comment]
> > Only the latest commit needs to be reviewed
> 
> Is this the one that updates craft-application to 2.4.0?

yes

**Review by cmatsuoka — APPROVED** [review]
LGTM. Also moving build-base settings from the extension to user if the extension is set and base is bare sounds like a sensible decision in the long term.

**Review by lengau — APPROVED** [review]

**Comment by lengau** [comment]
Rebased on main, should be ready to rebase-merge when CI completes

**Pull request merged**
