### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by jy5275**
- [ √] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Review by cjdcordeiro — COMMENTED** [review]
thanks for the fix @jy5275 . it lgtm , but could you please sign the [CLA](https://ubuntu.com/legal/contributors) :)

**Comment by jy5275** [comment]
> thanks for the fix @jy5275 . it lgtm , but could you please sign the [CLA](https://ubuntu.com/legal/contributors) :)

Done

**Review by clay-lake — APPROVED** [review]

**Review by tigarmo — APPROVED** [review]

**Comment by clay-lake** [comment]
Hi @jy5275, Our CLA check is still failing. 

Could you edit your CLA comment to use 'x' instead of '√'

For example:
```
[x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
```

**Review by cjdcordeiro — COMMENTED** [review]
all good now. thanks @jy5275

**Review by cjdcordeiro — APPROVED** [review]

**Pull request merged**
