### PR TITLE
now import Path directly from pathlib, and change get_provider in __g… …et_provider__.py

### PR DESCRIPTION
**Pull request by SamirPS**
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

### CODE REVIEW

**Comment by SamirPS** [comment]
@cjdcordeiro @cmatsuoka

**Comment by SamirPS** [comment]
?

**Comment by sergiusens** [comment]
thanks for your contribution, since this PR builds on top of the previous one, might be good to sort the issues on the prior one before triggering the tests for this one.

**Comment by SamirPS** [comment]
Ok no problem i wait for the other PR then

**Pull request closed without merging**
